In [1]:
import json

path = './corpus.jsonl'

with open(path, 'r') as f:
    corpus = [json.loads(line)['text'] for line in f]

In [17]:
import datasets
dataset = datasets.load_dataset('json', data_files=path, split='train')
dataset

Dataset({
    features: ['text'],
    num_rows: 2587
})

In [18]:
for i in range(10):
    print(dataset[i]['text'])
    print('-' * 100)

does not know that angles in a triangle sum to 180 degrees
----------------------------------------------------------------------------------------------------
uses dividing fractions method for multiplying fractions
----------------------------------------------------------------------------------------------------
believes there are 100 degrees in a full turn
----------------------------------------------------------------------------------------------------
thinks a quadratic without a non variable term, can not be factorised
----------------------------------------------------------------------------------------------------
believes addition of terms and powers of terms are equivalent e.g. a + c = a^c
----------------------------------------------------------------------------------------------------
when measuring a reflex angle, gives the acute or obtuse angle that sums to 360 instead
------------------------------------------------------------------------------------------------

In [21]:
path = "./queries_v2.jsonl"
dataset = datasets.load_dataset('json', data_files=path, split='train')
dataset
for i in range(10):
    print(dataset[i]['query'], dataset[i]['correct_id'])
    print('-' * 100)

simplify an algebraic fraction by factorising the numerator simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \) \( m+1 \) 2142.0
----------------------------------------------------------------------------------------------------
simplify an algebraic fraction by factorising the numerator simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \) \( m+2 \) 143.0
----------------------------------------------------------------------------------------------------
simplify an algebraic fraction by factorising the numerator simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \) \( m-1 \) 2142.0
----------------------------------------------------------------------------------------------------
recall and use the intersecting diagonals properties of a rectangle the angles highlighted on this rectangle with different length sides can never be... ![a rectangle with the diagonals drawn in. the angle on the right hand side at the centre is highlighted in red a

In [28]:
from transformers import AutoTokenizer, AutoModel
model_id = "BAAI/bge-small-en-v1.5"
d = {'text': 'does not know that angles in a triangle sum to 180 degrees'}
tokenizer = AutoTokenizer.from_pretrained(model_id)
ids = tokenizer(d['text'], max_length=128, padding=True, truncation=True,
                             return_tensors="pt")
ids


{'input_ids': tensor([[  101,  2515,  2025,  2113,  2008, 12113,  1999,  1037,  9546,  7680,
          2000,  8380,  5445,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [42]:
import torch
from transformers import AutoTokenizer, AutoModel
model_id = "BAAI/bge-small-en-v1.5"
tokenizer = AutoTokenizer.from_pretrained(model_id)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModel.from_pretrained(model_id).to(device)

In [43]:
d = {'text': 'uses dividing fractions method for multiplying fractions'}
ids = tokenizer(d['text'], padding=True, truncation=True,
                             return_tensors="pt")
model.eval()
with torch.no_grad():
    ids = ids.to(device)
    outputs = model(**ids)
    # embeddings = last_token_pool(outputs.last_hidden_state, features['attention_mask'])
    embeddings = outputs.last_hidden_state[:, 0]  # CLS token
    embeddings = torch.nn.functional.normalize(embeddings, p=2, dim=1)
    print(embeddings)

tensor([[-5.3867e-02,  3.1994e-03, -1.6951e-02, -6.9049e-02, -3.0075e-02,
         -3.8436e-02, -6.5766e-03, -3.3353e-02,  5.9543e-02,  3.3863e-02,
          1.3753e-02, -7.6120e-02, -1.4235e-02, -1.1288e-02,  2.3966e-02,
         -1.3862e-02, -3.0358e-02,  9.2968e-03, -1.8522e-02, -2.4247e-02,
          9.7753e-03, -4.4002e-02, -1.7134e-02, -7.5372e-03,  8.5100e-02,
          3.4938e-02, -3.3996e-02, -1.2213e-01, -5.3134e-02, -1.7060e-01,
          8.0506e-02,  3.3787e-03,  6.7322e-02, -3.7322e-02, -6.5864e-02,
         -2.4245e-02, -1.3552e-02,  4.5215e-02, -3.1878e-02,  1.7572e-02,
          1.5058e-02, -4.2877e-02,  3.5724e-02, -2.0317e-02, -3.1048e-03,
         -2.0955e-02, -6.5798e-02,  2.2393e-02,  1.0473e-01,  3.3058e-02,
          4.0727e-02, -1.5813e-02, -8.8412e-03,  1.9312e-03, -2.0983e-02,
          2.0654e-02,  4.1578e-02,  3.0341e-02,  1.9466e-02,  2.8379e-02,
          9.3157e-02,  3.2919e-02, -1.3207e-01,  3.1198e-02,  3.6531e-02,
         -6.6946e-02,  2.4984e-02, -2.

In [41]:
from FlagEmbedding import FlagModel
sentences_1 = ["uses dividing fractions method for multiplying fractions"]
model = FlagModel('BAAI/bge-small-en-v1.5',
                  use_fp16=False) # Setting use_fp16 to True speeds up computation with a slight performance degradation
embeddings_1 = model.encode(sentences_1)
print(embeddings_1)


You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


[[-5.38667627e-02  3.19937663e-03 -1.69507973e-02 -6.90493658e-02
  -3.00752297e-02 -3.84360589e-02 -6.57658745e-03 -3.33531164e-02
   5.95430210e-02  3.38625535e-02  1.37533555e-02 -7.61200637e-02
  -1.42346853e-02 -1.12881511e-02  2.39661802e-02 -1.38618322e-02
  -3.03578936e-02  9.29683819e-03 -1.85216218e-02 -2.42465585e-02
   9.77529120e-03 -4.40022238e-02 -1.71339009e-02 -7.53717171e-03
   8.51000249e-02  3.49384509e-02 -3.39957103e-02 -1.22133195e-01
  -5.31342402e-02 -1.70595080e-01  8.05058479e-02  3.37874098e-03
   6.73223808e-02 -3.73220108e-02 -6.58638924e-02 -2.42451373e-02
  -1.35524701e-02  4.52145375e-02 -3.18779461e-02  1.75721496e-02
   1.50582353e-02 -4.28771637e-02  3.57243642e-02 -2.03169417e-02
  -3.10484786e-03 -2.09549014e-02 -6.57979324e-02  2.23932322e-02
   1.04728520e-01  3.30577679e-02  4.07274663e-02 -1.58129372e-02
  -8.84115789e-03  1.93124672e-03 -2.09827367e-02  2.06543542e-02
   4.15777266e-02  3.03407162e-02  1.94660835e-02  2.83791404e-02
   9.31568

In [22]:
np.array([query_embedding])

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [23]:
import faiss
import numpy as np
# import torch

# 1. 初始化索引
dimension = 384  # BGE-small 模型的输出维度
index = faiss.IndexFlatL2(dimension)  # 使用L2距离的暴力检索索引

# 2. 将语料库的向量添加到索引中
# 假设 corpus_embeddings 是您的语料库编码后的向量
corpus_embeddings = np.zeros((50, dimension))
index.add(corpus_embeddings.astype('float32'))

# 3. 搜索最相似的向量
query_embedding = np.zeros(dimension)
k = 5  # 返回前k个最相似的结果

# 执行搜索
distances, indices = index.search(
    np.array([query_embedding]).astype('float32'), 
    k
)

In [15]:
distances, indices

(array([[0., 0., 0., 0., 0.]], dtype=float32), array([[1, 2, 3, 4, 0]]))

In [29]:
indices[:, :2]

array([[1, 2]])

In [57]:
import numpy as np


def apk(actual, predicted, k=25):
    """
    Computes the average precision at k.
    
    This function computes the average prescision at k between two lists of
    items.
    
    Parameters
    ----------
    actual : list of float
    predicted : numpy.ndarray
    k : int, optional
        The maximum number of predicted elements
        
    Returns
    -------
    score : double
            The average precision at k over the input lists
    """
    
    if not actual:
        return 0.0
    print(len(predicted))
    if len(predicted)>k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i,p in enumerate(predicted):
        print(p, actual)
        # first condition checks whether it is valid prediction
        # second condition checks if prediction is not repeated
        if p in actual and p not in predicted[:i]:
            print("hit")
            num_hits += 1.0
            score += num_hits / (i+1.0)

    return score / min(len(actual), k)

def mapk(actual, predicted, k=25):
    """
    Computes the mean average precision at k.
    
    This function computes the mean average prescision at k between two lists
    of lists of items.
    
    Parameters
    ----------
    actual : list
             A list of lists of elements that are to be predicted 
             (order doesn't matter in the lists)
    predicted : list
                A list of lists of predicted elements
                (order matters in the lists)
    k : int, optional
        The maximum number of predicted elements
        
    Returns
    -------
    score : double
            The mean average precision at k over the input lists
    """
    res = [apk(a,p,k) for a,p in zip(actual, predicted)]
    print(res)
    return np.mean(res)


In [60]:
type(predicted)

numpy.ndarray

In [61]:
actual = [1, 2]
predicted = np.array([[2,2,1], [1,2,3]])
mapk(actual, predicted)

3
2 1


TypeError: argument of type 'int' is not iterable